#회원 가입
POST http://localhost:8080/user/join
Content-Type: application/json

{
    "userId": "test",
    "password": "test"
}

###

#로그인
POST http://localhost:8080/user/login
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}

###
